### ISSUE TITLE
annoying css error in step dialogs

### ISSUE THREAD

**Issue by zaanposni** [zaanposni/discord-masz#355]
![grafik](https://user-images.githubusercontent.com/24491035/129055526-e9b212ea-c376-4abc-ac23-76ecb4bc7552.png)

```css
form {
    padding-top: 16px;
}

.mat-form-field {
    margin-bottom: 8px;
}
```
